var mongoose = require('mongoose');
var Schema 	 = mongoose.Schema;

var DMschema = new Schema({
	auditCode: {type: String, required: true},
	godiste: {type: Number, required: true},
	spol: {type: String, required: true},
	porodicna_anamneza: {type: Boolean, required: true},
	tipDM: {type: String, required: true},
	hospitalizacija: {type: Number, required: true},
	hba1c: {type: Boolean, required: true},
	ValHbA1C: String,
	glukoza: {type: Boolean, required: true},
	ValGlukoza: String,
	glukoza2: {type: Boolean, required: true},
	ValGlukoza2: String,
	ttv: {type: Boolean, required: true},
	bmi: {type: Boolean, required: true},
	tlak: {type: Boolean, required: true},
	ValTlak: String,
	holesterol: {type: Boolean, required: true},
	trigliceridi: {type: Boolean, required: true},
	mikroalb: {type: Boolean, required: true},
	stopalo: {type: Boolean, required: true},
	ocno_dno: {type: Boolean, required: true},
	monofilament: {type: Boolean, required: true},
	pusac: {type: Boolean, required: true},
	pusac_savjetovanje: Boolean,
	alkohol: {type: Boolean, required: true},
	edukacija: {type: Boolean, required: true},
	edukacija_edukator: String,
	samokontrola_glukoze: {type: Boolean, required: true},
	posjeta_spec: {type: Boolean, required: true},
	specijalisti: String,
	terapija_ljekar: String,
	oral_a: String,
	doza_a: String,
	oral_b: String,
	doza_b: String,
	oral_c: String,
	doza_c: String,
	inzulin: String,
	drugo_th: String,
	kontrola: {type: Boolean, required: true}
});

module.exports = mongoose.model('DiabetesAudit', DMschema);